### PR TITLE
intl_ru_RU.arb

### PR DESCRIPTION
**Pull request by FlutterNewbie**
added russian language

### CODE REVIEW

**Comment by kevin-sakemaer** [comment]
Thanks a lot for your contribution !
I will merge this tomorrow and generate new code from that.
Then I will publish a new version on pub 🙂

**Comment by FlutterNewbie** [comment]
Not a problem!
Thanks for the great package! 👍

**Review by kevin-sakemaer — APPROVED** [review]

**Comment by kevin-sakemaer** [comment]
package has been updated on pub :) 
https://pub.dev/packages/international_system_of_units

**Comment by FlutterNewbie** [comment]
Thanks a lot.
Sorry for the stupid question, but how to use it?
I have List with units.
List timeUnits = [
  TimeUnit.second,
  TimeUnit.minute,
  TimeUnit.hour,
  TimeUnit.day,
  TimeUnit.week,
  TimeUnit.month,
  TimeUnit.calendarYear,
];
and ru_RU default locale.

**Comment by kevin-sakemaer** [comment]
something like that ;) 
```dart
void main(List<String> arguments) async {
  final language = 'ru_RU';
  //  ignore: unused_local_variable
  final sIi18n =
      await InternationalSystemLocalizations.load(Locale.parse(language));
  Intl.defaultLocale = language;
  final isl =
      await InternationalSystemLocalizations.load(Locale.parse(language));

  print(isl.time.locale(60, UnitSystem.international,
      toInternationalUnit: TimeUnit.minute, shortUnit: false));
}
```

**Pull request merged**
